### ISSUE TITLE
USER STORY: Recipes filtering

### ISSUE THREAD

**Issue by lestece** [lestece/myKTCN#13]
As a **Site User**, I can **search through the recipes by category or name** so that **I can quickly locate the recipe I'm looking for**.

## Acceptance Criteria:
1. A search bar should be visible in the user's Cookbook page and the Browse recipes page.
2. The search bar should filter the recipes if the title or ingredients contain the inputted value
3. A select box should appear to allow users to filter recipes by category
## Tasks:
- [x] Add a search bar to the Browse recipes page and user Cookbook page
- [x] In the views for RecipeList and UserRecipes, add a condition that filters the recipes by inputted value in the search bar. Return the ones that contain the value in the title or ingredients.
- [x] Install django filter and create filterset that filters by category field choices
