### ISSUE TITLE
USER STORY: Browse Recipes

### ISSUE THREAD

**Issue by lestece** [lestece/myKTCN#2]
As a **Site User**, I can **view a paginated list of recipes** so that **I can choose and select the ones I am interested in**.

## Acceptance Criteria:
1. Navigating to the "Browse recipes" page, a list of recipes made public is displayed
2. Each recipe appears as a card, showing a related image, the category it belongs to, its title, a small clip of the description, the author and level of difficulty
3. A click on the recipe's card brings the user to the full recipe page

## Tasks:
- [x] Create a RecipeList class in the views to retrieve a list of all public recipes in the database
- [x] Create the HTML template for the browse recipes page
- [x] Use Bootstrap cards to create the responsive recipe cards
- [x] Link the recipe cards to their related recipe detail page
- [x] Add pagination
