### ISSUE TITLE
USER STORY: Recipe Rating

### ISSUE THREAD

**Issue by lestece** [lestece/myKTCN#7]
As a **Site User**, I can **rate other users' recipes** so that **I can leave a feedback about them**.

## Acceptance Criteria:
1. A star rating should appear on each recipe details page
2. By clicking on the rating system, a logged in user should be able to rate the recipe (if not the author of that recipe)
3. When re-clicking on the rating system, logged in users should be able to change their previous rating if a mistake was made

## Tasks:
- [x] Create a Rating class in the models for each rating, with attributes for the recipe that was rated and the user who made the rating
- [x] Calculate the avg rating in the Recipe class using the aggregate function
- [x] In the views.py, check if the user has already made any rating. If so, display it, otherwise delete the previous rating and save the new submitted one
- [x] Add the star rating system to the recipe details HTML template
