### ISSUE TITLE
USER STORY: New User Signup

### ISSUE THREAD

**Issue by lestece** [lestece/myKTCN#8]
As a **Site User**, I can **create an account** so that **I can add, edit and delete recipes in my cookbook, choose which ones to share with the Community and interact with other users' recipes**.

## Acceptance Criteria:
1. A signup button should always be visible when users are not logged in/signed up
2. When the button is clicked, users should be brought to the sign up form
3. A new account should be created when the user fills in the details and clicks on the Create Account button
4. A logged in confirmation should be made visible to notify the user of a successful registration

## Tasks:
- [x] Add a sign up button to the Navbar
- [x] Install django allauth 
- [x] Customize the allauth sign up form in the templates so that it's consistent with the site
- [x] Use django messages to let the user know they successfully signed up
