### ISSUE TITLE
USER STORY: User Login and Logout

### ISSUE THREAD

**Issue by lestece** [lestece/myKTCN#9]
As a **Site User**, I can **login and logout from my account** so that **it stays secure**.

## Acceptance Criteria:
1. If the user is logged out, a login button should always be visible in the navbar
2. When the login button is clicked, the user should be brought to the login page
3. When the user submits the right credentials, they should be instantly logged in
4. If invalid credentials are provided, a message displaying that the information entered is incorrect should be displayed
5. A message should display that the user has been successfully logged in
6. If the user is logged in and clicks on the logged out button, a confirmation request should be displayed before proceeding
7. A message should display that the user has been logged out successfully

## Tasks:
- [x] Have django allauth installed
- [x] Add login/logout buttons to the Navbar
- [x] Customize the login and logout templates so that they're consistent with the site
- [x] Use django messages to inform the user of successful logging in/out or errors with credentials
